FROM marvambass/nginx-ssl-secure

RUN apt-get install curl
RUN curl --silent --location https://deb.nodesource.com/setup_0.12 | bash -
RUN apt-get install --yes nodejs

RUN mkdir /var/www

ADD kibitz.js /var/www/kibitz.js
